CREATE DATABASE IF NOT EXISTS coder_database;

USE coder_database;

CREATE TABLE IF NOT EXISTS Areas (
  ID_Areas INT NOT NULL,
  Provincia VARCHAR(50) NOT NULL,
  Partido VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Areas)
);

CREATE TABLE IF NOT EXISTS Sucursal(
  ID_Sucursal  INT UNIQUE NOT NULL AUTO_INCREMENT,
  ID_Areas INT  NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Domicilio VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Sucursal),
  FOREIGN KEY (ID_Areas) REFERENCES Areas (ID_Areas)
);

CREATE TABLE IF NOT EXISTS Empleado(
  ID_Empleado INT UNIQUE NOT NULL,
  Apellido VARCHAR(50) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Telefono INT NOT NULL,
  Email VARCHAR(30) NOT NULL,
  Domicilio VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Empleado)
);

CREATE TABLE IF NOT EXISTS Socio(
  ID_Socio INT UNIQUE NOT NULL AUTO_INCREMENT,
  Apellido VARCHAR(50) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  Telefono INT NOT NULL,
  Email VARCHAR(30) NOT NULL,
  PRIMARY KEY (ID_Socio)
);

CREATE TABLE IF NOT EXISTS Carnet(
  ID_Carnet INT UNIQUE NOT NULL AUTO_INCREMENT,
  ID_Socio INT UNIQUE NOT NULL,
  Apellido VARCHAR(50) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Socio),
  FOREIGN KEY (ID_Socio) REFERENCES Socio (ID_Socio)
);

CREATE TABLE IF NOT EXISTS Autor(
  ID_Autor INT UNIQUE NOT NULL,
  Apellido VARCHAR(50) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Autor)
);
CREATE TABLE IF NOT EXISTS Autor(
  ID_Autor INT UNIQUE NOT NULL,
  Apellido VARCHAR(50) NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Autor)
);
CREATE TABLE IF NOT EXISTS Editorial(
  ID_Editorial INT UNIQUE NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Editorial)
);
CREATE TABLE IF NOT EXISTS Genero(
  ID_Genero INT UNIQUE NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Genero)
);

CREATE TABLE IF NOT EXISTS Libros(
  ID_Libros INT UNIQUE NOT NULL AUTO_INCREMENT ,
  ID_Autor INT UNIQUE NOT NULL,
  ID_Editorial INT UNIQUE NOT NULL,
  ID_Genero INT UNIQUE NOT NULL,
  Precio INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Libros),
  FOREIGN KEY (ID_Autor) REFERENCES Autor(ID_Autor),
  FOREIGN KEY (ID_Editorial) REFERENCES Editorial (ID_Editorial),
  FOREIGN KEY (ID_Genero) REFERENCES Genero (ID_Genero)
);
CREATE TABLE IF NOT EXISTS CDs(
  ID_CDs INT UNIQUE NOT NULL AUTO_INCREMENT,
  ID_Autor INT UNIQUE NOT NULL,
  ID_Editorial INT UNIQUE NOT NULL,
  ID_Genero INT UNIQUE NOT NULL,
  Precio INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_CDs),
  FOREIGN KEY (ID_Autor) REFERENCES Autor(ID_Autor),
  FOREIGN KEY (ID_Editorial) REFERENCES Editorial (ID_Editorial),
  FOREIGN KEY (ID_Genero) REFERENCES Genero (ID_Genero)
);
CREATE TABLE IF NOT EXISTS Revistas(
  ID_Revistas INT UNIQUE NOT NULL AUTO_INCREMENT,
  ID_Autor INT UNIQUE NOT NULL,
  ID_Editorial INT UNIQUE NOT NULL,
  ID_Genero INT UNIQUE NOT NULL,
  Precio INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Revistas),
  FOREIGN KEY (ID_Autor) REFERENCES Autor(ID_Autor),
  FOREIGN KEY (ID_Editorial) REFERENCES Editorial (ID_Editorial),
  FOREIGN KEY (ID_Genero) REFERENCES Genero (ID_Genero)
);

CREATE TABLE IF NOT EXISTS Proveedor(
  ID_Proveedor INT UNIQUE NOT NULL,
  Razon_Social VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  Domicilio VARCHAR(50) NOT NULL,
  Telefono INT NOT NULL,
  PRIMARY KEY (ID_Proveedor)
);

CREATE TABLE IF NOT EXISTS Productos(
  ID_Productos INT UNIQUE NOT NULL,
  Cantidad INT NOT NULL,
  Nombre VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Productos)
  );



CREATE TABLE IF NOT EXISTS Metodos_de_Pago(
  ID_Metodos_de_Pago INT UNIQUE NOT NULL,
  Metodo_de_Pago VARCHAR(50) NOT NULL,
  Entidad_Financiera VARCHAR(50) NOT NULL,
  PRIMARY KEY (ID_Metodos_de_Pago)
);

CREATE TABLE IF NOT EXISTS Ventas(
  ID_Ventas INT UNIQUE NOT NULL AUTO_INCREMENT,
  ID_Productos INT UNIQUE NOT NULL,
  ID_Metodos_de_Pago INT UNIQUE NOT NULL,
  Fecha DATE NOT NULL,
  Cantidad INT NOT NULL,
  Total FLOAT NOT NULL,
  PRIMARY KEY (ID_Ventas),
  FOREIGN KEY (ID_Productos) REFERENCES Productos(ID_Productos),
  FOREIGN KEY (ID_Metodos_de_Pago) REFERENCES Metodos_de_Pago (ID_Metodos_de_Pago)
);

CREATE TABLE IF NOT EXISTS Compras(
  ID_Compras INT UNIQUE NOT NULL AUTO_INCREMENT,
  ID_Productos INT UNIQUE NOT NULL,
  ID_Proveedor INT UNIQUE NOT NULL,
  Fecha DATE NOT NULL,
  Cantidad INT NOT NULL,
  Total FLOAT NOT NULL,
  PRIMARY KEY (ID_Compras),
  FOREIGN KEY (ID_Productos) REFERENCES Productos(ID_Productos),
  FOREIGN KEY (ID_Proveedor) REFERENCES Proveedor (ID_Proveedor)
);

